learn_url/learn_url/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from url_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('url_app.urls')),
    path('admin/', admin.site.urls),
]

learn_url/url_app/urls.py
from django.conf.urls import url
from url_app import views

app_name = "url_app"

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),

]

learn_url/url_app/models.py
from django.db import models

# Create your models here.

learn_url/url_app/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    my_dic = {"chance": " Hi my last kid is Puvi"}
    return render(request, 'basic_app/index.html', context=my_dic)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url.html')

learn_url/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Puvi Naturals</a>
        <a class="nav-link" href="{% url 'index' %}">Home</a>
        <a class="nav-link" href="{%  url 'url_app:other' %}"> other</a>
        <a class="nav-link" href="{% url 'url_app:relative' %}">Relative</a>
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>

      </nav>



<div class="container">
  {% block body_block %}

  {% endblock %}
</div>


  </body>
</html>

learn_url/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}
<h1> Welcome to Home page</h1>
<h3> Hi I 'm Chandrasekar'</h3>


 <h3>{{ chance|cut:'kid' }}</h3>
 <h4>Today date is {{ now }}</h4>

 {% endblock %}

learn_url/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

  <h1> Welcome to other</h1>

{% endblock %}

learn_url/templates/basic_app/relative_url.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}
<h1>Welcome to relative</h1>
{% endblock%}